### ISSUE TITLE
Show instances are surprising

### ISSUE THREAD

**Issue by emilypi** [PaulJohnson/Haskell-Decimal#20] opened 2019-10-22 18:54 UTC
Hey @PaulJohnson 

Would you accept a PR making the `Show` instance flush with the other decimal Haskell types? Currently, the behavior contrasts in the following way: 

```
П> show @Decimal 2.0
"2"
П> show @Decimal 2
"2"
П> show @Double 2
"2.0"
П> show @Double 2.0
"2.0"
```

This poses a subtle problem when working with stringly-typed APIs and JSON. In the latter case, if read as raw json, `2` is inferred to be an `integer` type, but `2.0` is a `number`. What are your thoughts on this?

**Comment by ericpashman** [comment] 2019-10-22 21:00
I believe this is another manifestation of #14. The problem is in GHC's handling of numeric literals. If anybody can figure out precisely why this happens, it may merit a bug report on the GHC tracker.

I don't work on GHC, but the relevant bits seem to be in the definition of the [`readRational__`[(https://github.com/ghc/ghc/blob/2d2cc76ffb781d01c800608cd8be05cca67ac4c0/compiler/utils/Util.hs#L1140) function, which is used by the lexer. The question is whether there's a simple way to preserve information about zeros after the decimal point without screwing up the handling of other numeric literals.

**Comment by PaulJohnson** [comment] 2019-10-23 07:49
@ericpashman is correct. There is nothing straightforward to do about this. However if you are using the `Read` instance rather than Haskell literals then it does the Right Thing:

`Prelude Data.Decimal> read "2.0" :: Decimal`
`2.0`
`Prelude Data.Decimal> read "2.0000" :: Decimal`
`2.0000`
`Prelude Data.Decimal> read "2" :: Decimal`
`2`

Closing this as a dupe.

**Closed by PaulJohnson** 2019-10-23 07:49 UTC
Labels: duplicate

**Comment by PaulJohnson** [comment] 2019-10-23 08:03
Sorry, not to re-open, but I just figured out what your actual problem is. Its that you have a Haskell writer and a dynamically-typed reader for your JSON, not the other way round. So when your Haskell writes "2" the dynamically typed reader assumes this is an Integer when it ought to be a Real, presumably causing subtle arithmetic bugs further in.

The workaround is to ensure that the value being written has `decimalPlaces` of at least 1, like this:

`notInteger v = roundTo (max 1 $ decimalPlaces v) v`

`Prelude Data.Decimal> notInteger 3.321`
`3.321`
`Prelude Data.Decimal> notInteger 2`
`2.0`
